# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3'
services:
  consul:
    image: docker.io/bitnami/consul:1.18.0
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - "8300:8300"
      - "8500:8500"
      - "8600:8600"
    command: consul agent -dev -ui -client 0.0.0.0 -log-level=INFO
